### ISSUE TITLE
Flow features extraction

### ISSUE THREAD

**Issue by gubertoli** [nprint/pcapml_fe#1]
Awesome work with pcapML and the standardization for network datasets through pcapng.

This question is more a new feature/request, are there plans to generate flow features extraction similar to the NetFlow and CICFlowMeter with pcapML_FE (aggregating by sampleID) ?

**Comment by JordanHolland** [comment]
Hey, apologies for missing this, I didn't have notifications set up on this repository on accident.

There are no plans to generate flow features or the like. Our goal is to standardize the tasks themselves at the dataset level and therefore make new methods directly comparable with each other (`pcapML`) and then make feature extraction as simple and easy as possible to speed up the process of innovation (`pcapML_FE`).  

We released a paper about `pcapML`, `pcapML_FE` and the goals of the project [here](https://arxiv.org/pdf/2203.12410.pdf)

If this doesn't answer your question let me know, happy to continue this thread (now that I have notifications on)
